version: 1.0
publish: app
services:
  app:
    command: npm install
    environment:
      debug: 'app:*'
      app_password: 'testing'
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    ports:
      - container: 3000
        public: 80
  